---
# This playbook contains common plays that will be run on all nodes.
#
# Para ejecutar solo este playbook
# - hosts : all
#  remote_user: ansible
#  become: yes
#  tasks:
#
# Se debe modificar el codigo porque ntp fue removido de la version CentOS 8. Se agregan Facts
    - name: Install chrony for Centos 8
      dnf:
        name: chrony 
        state: present
      tags: chrony
      when: ansible_distribution == "CentOS" or
            ansible_distribution_major_version == "8"

# Para versiones Debian instalacion de chrony
    - name: Install Chrony on Debian
      apt: name=chrony state=present
      tags: chrony
      when: ansible_os_family == "Debian"

# Se corrige debido a que el look esta deprecated
#    - name: Install common dependencies
#      yum: name={{ item }} state=installed
#      with_items:
#      - libselinux-python
#      - libsemanage-python
#      - firewalld
# Se instalan las dependecias en CentOS 8
    - name: Install common dependencies on CentOS 8
      dnf:
        name: "{{ dependencies }}"
        state: installed
      vars:
        dependencies:
        - python3-libselinux
        - python3-libsemanage
# El paquete firewalld ya esta instalado, quizas hay que usar este?
#        - python3-firewall
      when: ansible_distribution == "CentOS" or
            ansible_distribution_major_version == "8"

# Se instalan las dependecias en Debian
    - name: Install common dependencies on Debian
      apt:
        name: "{{ dependencies }}"
        state: present
      vars:
        dependencies:
        - python3-selinux
        - python3-semanage
        - policycoreutils
        - selinux-utils
        - selinux-basics
# El paquete firewalld ya esta instalado, quizas hay que usar este?
#        - python3-firewall
      when: ansible_os_family == "Debian"

# Se instalan las dependecias en CentOS
    - name: Install common dependencies on CentOS
      dnf:
        name: "{{ dependencies }}"
        state: present
      vars:
        dependencies:
        - python3-libselinux
        - python3-libsemanage
        - policycoreutils-python-utils
# El paquete firewalld ya esta instalado, quizas hay que usar este?
#        - python3-firewall
      when: ansible_os_family == "RedHat"

# Configura el archivo chrony
    - name: Configure Chrony file
      template: 
        src: "/root/obligatorio/obligatorio_2021_08/lamp/roles/common/templates/chrony.conf.j2"
        dest: "/etc/chrony.conf"
        mode: 0600
      tags: chrony
      notify: restart chrony
# Se comenta el when porque es necesario para los sistemas
#      when: ansible_distribution == "CentOS" or
#            ansible_distribution_major_version == "8"

# Se comenta porque los paquetes ntp ya no es usado en las nuevas versiones
#    - name: Configure ntp file
#      template: 
#        src: "ntp.conf.j2"
#        dest: "/etc/ntp.conf"
#        mode: 0600
#      tags: ntp
#      notify: restart ntp

# Se comenta porque no se utiliza mas el paquete ntp
# Iniciar servicio de ntp
#    - name: Start the ntp service
#      service: 
#        name: ntpd
#        state: started
#        enabled: yes
#      tags: ntp

# Iniciar servicio de chronyd
    - name: Start the chrony service
      service:
        name: chronyd
        state: started
        enabled: yes
      tags: chrony
#      when: ansible_distribution == "CentOS" or
#            ansible_distribution_major_version == "8"