---
# This playbook will install MariaDB and create db user and give permissions.

# Se instala los paquetes en CentOS
- name: Install MariaDB package for CentOS
  yum: 
    name: "{{ paquetes }}"
    state: installed
  vars:
    paquetes:
      - mariadb-server
# Se instalan paquetes de python
      - python3-pip
      - python-mysqldb
  when: ansible_os_family == "RedHat"

# Se instalan los paquetes para Debian
- name: Install MariaDB package for Debian
  apt: 
    name: "{{ paquetes }}"
    state: installed
  vars:
    paquetes:
      - mariadb-server
      - python3-mysqldb
  when: ansible_os_family == "Debian"

# Configuracion de SeLinux
- name: Configure SELinux to start mysql on any port
  seboolean: 
    name: mysql_connect_any
    state: true
    persistent: yes

- name: Create Mysql configuration file
  template: 
    src: "/root/obligatorio/obligatorio_2021_08/lamp/roles/db/templates/my.cnf.j2"
    dest: "/etc/my.cnf"
    mode: 0600
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: 
    path: /var/log/mysqld.log 
    state: touch
    owner: mysql
    group: mysql
    mode: 0775

- name: Create MariaDB PID directory
  file:
    path: /var/run/mysqld
    state: directory
    owner: mysql
    group: mysql
    mode: 0775

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
